# Generated by Django 5.1.3 on 2024-11-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('km_pistas', models.DecimalField(decimal_places=2, help_text='Longitud total esquiable en kilómetros', max_digits=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='appSkiStick.localizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_de_pista', models.CharField(help_text='Tipo de pista: Verde, Azul, Roja, Negra o Competición', max_length=20)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='appSkiStick.estacion')),
            ],
        ),
    ]
