# Generated by Django 5.1.3 on 2024-11-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('verde', 'Verde'), ('azul', 'Azul'), ('roja', 'Roja'), ('negra', 'Negra'), ('competicion', 'Competición')], max_length=20, unique=True)),
                ('nivel', models.CharField(editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('km_pistas', models.DecimalField(decimal_places=2, help_text='Longitud total esquiable en kilómetros', max_digits=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='appSkiStick.localizacion')),
            ],
        ),
        migrations.CreateModel(
            name='EstacionTipoDePista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Número de pistas de este tipo en la estación')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSkiStick.estacion')),
                ('tipo_de_pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSkiStick.tipodepista')),
            ],
            options={
                'unique_together': {('estacion', 'tipo_de_pista')},
            },
        ),
    ]
