# Generated by Django 5.1.3 on 2024-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='tipos_pista',
            field=models.ManyToManyField(related_name='estaciones', through='appSkiStick.EstacionTipoDePista', to='appSkiStick.tipodepista'),
        ),
    ]
