# Generated by Django 5.1.3 on 2024-11-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0002_estacion_tipos_pista'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estaciones/', verbose_name='imagen'),
        ),
    ]
