# Generated by Django 5.1.3 on 2024-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0003_estacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='imagen_plano',
            field=models.ImageField(blank=True, null=True, upload_to='estaciones/', verbose_name='imagen_plano'),
        ),
    ]
