# Generated by Django 5.1.2 on 2024-11-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0004_estacion_imagen_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacion',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localizacion',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
