# Generated by Django 5.1.3 on 2024-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0005_localizacion_latitud_localizacion_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodepista',
            name='bandera',
            field=models.ImageField(blank=True, null=True, upload_to='pistas/', verbose_name='bandera_pista'),
        ),
        migrations.AddField(
            model_name='tipodepista',
            name='descripcion_corta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipodepista',
            name='descripcion_larga',
            field=models.TextField(blank=True, null=True),
        ),
    ]
