# Generated by Django 5.1.3 on 2024-11-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0007_localizacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estaciones/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='imagen_plano',
            field=models.ImageField(blank=True, null=True, upload_to='estaciones/', verbose_name='Track Map'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='km_pistas',
            field=models.DecimalField(decimal_places=2, help_text='Total skiable length in kilometers', max_digits=5, verbose_name='Skiable Kilometers'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='appSkiStick.localizacion', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='tipos_pista',
            field=models.ManyToManyField(related_name='estaciones', through='appSkiStick.EstacionTipoDePista', to='appSkiStick.tipodepista', verbose_name='Track Types'),
        ),
        migrations.AlterField(
            model_name='estaciontipodepista',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, help_text='Number of tracks of this type in the station', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='estaciontipodepista',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSkiStick.estacion', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='estaciontipodepista',
            name='tipo_de_pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSkiStick.tipodepista', verbose_name='Track Type'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='localizacion/', verbose_name='Location Image'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='bandera',
            field=models.ImageField(blank=True, null=True, upload_to='pistas/', verbose_name='Track Flag'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='descripcion_corta',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='descripcion_larga',
            field=models.TextField(blank=True, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='nivel',
            field=models.CharField(editable=False, max_length=20, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='nombre',
            field=models.CharField(choices=[('verde', 'Green'), ('azul', 'Blue'), ('roja', 'Red'), ('negra', 'Black'), ('competicion', 'Competition')], max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
