# Generated by Django 5.1.3 on 2024-11-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0008_alter_estacion_descripcion_alter_estacion_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estaciones/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='imagen_plano',
            field=models.ImageField(blank=True, null=True, upload_to='estaciones/', verbose_name='Plano de las Pistas'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='km_pistas',
            field=models.DecimalField(decimal_places=2, help_text='Longitud total esquiable en kilómetros', max_digits=5, verbose_name='Kilómetros Esquiables'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='appSkiStick.localizacion', verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='tipos_pista',
            field=models.ManyToManyField(related_name='estaciones', through='appSkiStick.EstacionTipoDePista', to='appSkiStick.tipodepista', verbose_name='Tipos de Pista'),
        ),
        migrations.AlterField(
            model_name='estaciontipodepista',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, help_text='Número de pistas de este tipo en la estación', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='estaciontipodepista',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSkiStick.estacion', verbose_name='Estación'),
        ),
        migrations.AlterField(
            model_name='estaciontipodepista',
            name='tipo_de_pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSkiStick.tipodepista', verbose_name='Tipo de Pista'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='localizacion/', verbose_name='Imagen de la Localización'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='bandera',
            field=models.ImageField(blank=True, null=True, upload_to='pistas/', verbose_name='Bandera de la Pista'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='descripcion_corta',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='descripcion_larga',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Larga'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='nivel',
            field=models.CharField(editable=False, max_length=20, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='tipodepista',
            name='nombre',
            field=models.CharField(choices=[('verde', 'Verde'), ('azul', 'Azul'), ('roja', 'Roja'), ('negra', 'Negra'), ('competicion', 'Competición')], max_length=20, unique=True, verbose_name='Nombre'),
        ),
    ]
