# Generated by Django 5.1.2 on 2024-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0009_alter_estacion_descripcion_alter_estacion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='localizacion',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='localizacion',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='localizacion',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='localizacion',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='tipodepista',
            name='descripcion_corta_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AddField(
            model_name='tipodepista',
            name='descripcion_corta_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AddField(
            model_name='tipodepista',
            name='descripcion_larga_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Larga'),
        ),
        migrations.AddField(
            model_name='tipodepista',
            name='descripcion_larga_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Larga'),
        ),
    ]
