# Generated by Django 5.1.2 on 2024-12-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0010_estacion_descripcion_en_estacion_descripcion_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodepista',
            name='nombre',
            field=models.CharField(choices=[('verde', 'Verde'), ('azul', 'Azul'), ('roja', 'Roja'), ('negra', 'Negra'), ('competición', 'Competición')], max_length=20, unique=True, verbose_name='Nombre'),
        ),
    ]
