# Generated by Django 5.1.3 on 2024-12-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0011_alter_tipodepista_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodepista',
            name='nombre_en',
            field=models.CharField(choices=[('verde', 'Verde'), ('azul', 'Azul'), ('roja', 'Roja'), ('negra', 'Negra'), ('competición', 'Competición')], max_length=20, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='tipodepista',
            name='nombre_es',
            field=models.CharField(choices=[('verde', 'Verde'), ('azul', 'Azul'), ('roja', 'Roja'), ('negra', 'Negra'), ('competición', 'Competición')], max_length=20, null=True, unique=True, verbose_name='Nombre'),
        ),
    ]
