# Generated by Django 4.2.17 on 2024-12-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0011_alter_tipodepista_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='incidentes/')),
                ('datos_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('ubicacion_pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='appSkiStick.tipodepista')),
            ],
        ),
    ]
