# Generated by Django 4.2.17 on 2024-12-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSkiStick', '0012_incidente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidente',
            old_name='foto',
            new_name='fotos',
        ),
        migrations.AlterField(
            model_name='incidente',
            name='datos_contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='ubicacion_pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='appSkiStick.localizacion'),
        ),
    ]
